import type { Metadata } from "next";
import { useRouter } from "next/router";
import { Nunito } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/Navbar";
import { Footer } from "./components/footer/Footer";
import getCurrentUser from "./acctions/getCurrentUser";
import ClientOnly from "./components/ClientOnly";
import Modal from "./components/modals/Modal";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import GanadoModal from "./components/modals/GanadoModal";
import { Sponsors } from "./components/sponsors/Sponsors";
import { SpeedInsights } from "@vercel/speed-insights/next";

const inter = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Feria Fongal 2024",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`${inter.className} site`}>
        <br />
        <br />
        <br />
        <br />
        <section className="bienvenida text-center mb-12">
          <h2 className="text-4xl font-bold text-green-900 mb-4">
            Bienvenido al Concurso Ganadero
          </h2>
          <p className="text-xl text-green-800">
            Descubre y celebra la belleza de nuestros concursantes!
          </p>
        </section>

        <section className="bg-gradient-to-r from-yellow-200 via-green-300 to-yellow-200 rounded-lg shadow-xl p-8 mb-12">
          <h3 className="text-3xl font-bold text-green-800 text-center mb-8">
            Ganadores
          </h3>
          <div className="flex justify-around">
            {["2do Lugar", "1er Lugar", "3er Lugar"].map((place, index) => (
              <div key={index} className="text-center">
                <div className="w-24 h-24 mx-auto mb-4 bg-yellow-400 rounded-full flex items-center justify-center">
                  <span className="text-4xl">🏆</span>
                </div>
                <h3 className="text-xl font-bold text-green-800">{place}</h3>
                <p className="text-green-700">por concursar...</p>
              </div>
            ))}
          </div>
        </section>

        <ClientOnly>
          <NavBar />
          <LoginModal />
          <RegisterModal />
          <main className="site-content">{children}</main>
          <div>
            {/* Your other components */}
            <Footer />
          </div>
          {/*<Sponsors/>*/}
        </ClientOnly>
      </body>
    </html>
  );
}
